### ISSUE TITLE
SSL does not work as described in the documentation

### ISSUE THREAD

**Issue by AuspeXeu** [dmurvihill/courier#41]
The following code
```
  val mailer = Mailer("example.com", 587)
    .auth(true)
    .as("me@myself.com", "pwd")
    .ssl(true)()
```

gives me `value ssl is not a member of courier.Session.Builder`

**Comment by daddykotex** [comment]
I believe the doc says `.startTls(true)()`, can you try this?

**Comment by daddykotex** [comment]
Sorry, for the confusion. What version of the library to you use?

**Comment by daddykotex** [comment]
Ok, I'm sorry. I'm a new maintainer. I'm still a little bit unfamiliar with the code base. I've merged the `ssl` feature last night. The code is not yet published.

The code you have relates to: https://github.com/dmurvihill/courier/tree/0.1.4

I'm planning to publish later today. I will close this when I publish with the version you can use to leverage this new feature.

**Comment by AuspeXeu** [comment]
Thanks :)

**Comment by daddykotex** [comment]
The release is in: https://github.com/dmurvihill/courier/releases/tag/v1.0.0-RC1

The 1.0.0-RC1 should be in maven central in a few minutes/hours. Let me know how it goes!

**Comment by AuspeXeu** [comment]
Works fine, thanks :)
