### ISSUE TITLE
upgrade to 2.13

### ISSUE THREAD

**Issue by fabianpage** [dmurvihill/courier#48]
Are there plans to upgrade to 2.13?

**Comment by daddykotex** [comment]
I think it's only a MR away. This code base is so small, I think it's a matter of minutes.

**Comment by daddykotex** [comment]
Well, scalatest is not yet available.

I'll try with 3.1.0-SNAP13, but I'll wait an official release before releasing a courier 2.0.0.

**Comment by fabianpage** [comment]
Sorry i didn't saw your mr. Actually scalatest 3.0.8 seems to be fine.

**Comment by daddykotex** [comment]
I've seen that thanks to your pull request :)

**Comment by AuspeXeu** [comment]
I saw you merged the PR, when will this be available on maven central etc? :)

**Comment by daddykotex** [comment]
I'm publishing as we speak, it's been a while though and my setup is not finish yet, but it will be done by the end of the day.

**Comment by AuspeXeu** [comment]
That's fantastic news, burning to upgrade to the new Scala version and you're the last missing dependency. Really excited! Thanks for your work! :)

**Comment by daddykotex** [comment]
It's published for 2.11, 2.12 and 2.13. It should be sync in the next 10-15 minutes.

Thanks to everyone, especially @fabianpage

**Comment by fabianpage** [comment]
@daddykotex Thanks for publishing.
